### ISSUE TITLE
not really an issue, more of a question

### ISSUE THREAD

**Issue by joe-wojniak** [osvaldokalvaitir/reactjs-desafio1#29]
Hi Osvaldo,

I just got a Rocketbook and I'd like to customize its OCR.  I see that you developed an app to interact with Rocketbook- can I replace the off-the-shelf OCR used with Rocketbook or does it need to be a standalone app that passes data/files to Rocketbook app? thx.

-Joe W.

**Comment by osvaldokalvaitir** [comment]
Hi, I think there was a misunderstanding. This is just the name of the application I learned in the course, it has nothing to do with Rocketbook
